language: php

dist: trusty

php:
  - 7.2
  - 7.1
  - 7.0
  - nightly

env:
  - SYMFONY_VERSION=2.7.* SOLR_VERSION=6.6.5
  - SYMFONY_VERSION=3.3.* SOLR_VERSION=6.6.5
  - SYMFONY_VERSION=4.0.* SOLR_VERSION=6.6.5
  - SYMFONY_VERSION=4.0.* SOLR_VERSION=7.5.0

cache:
  directories:
    - $HOME/.composer/cache
    - solr_downloads

before_install:
  - composer global require "hirak/prestissimo:^0.3"
  - ls solr_downloads/
  - wget -nc --continue -v --tries=3 --directory-prefix=solr_downloads "http://ftp.halifax.rwth-aachen.de/apache/lucene/solr/${SOLR_VERSION}/solr-${SOLR_VERSION}.tgz"
  - tar -xzf solr_downloads/solr-${SOLR_VERSION}.tgz

before_script:
#  - pecl install pecl_http
  - composer require --prefer-source --dev symfony/event-dispatcher:${SYMFONY_VERSION}
  - solr-${SOLR_VERSION}/bin/solr start -e techproducts
  # make configSet's available for techproducts instance
  - cp -R  solr-${SOLR_VERSION}/server/solr/configsets solr-${SOLR_VERSION}/example/techproducts/solr/

script:
  - vendor/bin/phpunit -c phpunit.xml.travis -v

after_success:
  - travis_retry php vendor/bin/coveralls -v

matrix:
  exclude:
      - php: 7.0
        env: SYMFONY_VERSION=4.0.* SOLR_VERSION=6.6.5
      - php: 7.0
        env: SYMFONY_VERSION=4.0.* SOLR_VERSION=7.5.0
  allow_failures:
      - php: nightly

sudo: false
