language: php

dist: trusty

php:
  - 7.2
  - 7.1
  - 7.0
  - hhvm
  - nightly

env:
  - SYMFONY_VERSION=2.8.* SOLR_VERSION=6.6.2
  - SYMFONY_VERSION=3.0.* SOLR_VERSION=6.6.2
  - SYMFONY_VERSION=4.0.* SOLR_VERSION=6.6.2
  - SYMFONY_VERSION=4.0.* SOLR_VERSION=7.2.0

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer global require "hirak/prestissimo:^0.3"
  - curl -O http://archive.apache.org/dist/lucene/solr/${SOLR_VERSION}/solr-${SOLR_VERSION}.tgz
  - tar -xzf solr-${SOLR_VERSION}.tgz

before_script:
#  - pecl install pecl_http
  - composer require --prefer-source --dev symfony/event-dispatcher:${SYMFONY_VERSION}
  - solr-${SOLR_VERSION}/bin/solr start -e techproducts

script: vendor/bin/phpunit -c phpunit.xml.travis -v

after_success:
  - travis_retry php vendor/bin/coveralls -v

matrix:
  exclude:
      - php: 7.0
        env: SYMFONY_VERSION=4.0.* SOLR_VERSION=6.6.2
      - php: 7.0
        env: SYMFONY_VERSION=4.0.* SOLR_VERSION=7.2.0
      - php: hhvm
        env: SYMFONY_VERSION=4.0.* SOLR_VERSION=6.6.2
      - php: hhvm
        env: SYMFONY_VERSION=4.0.* SOLR_VERSION=7.2.0
  allow_failures:
      - php: nightly

sudo: false
