language: php

dist: trusty

php:
  - 7.3
  - 7.2
  - nightly

env:
  - SYMFONY_VERSION=4.2.* SOLR_VERSION=8.0.0 SOLR_CLOUD=true
  - SYMFONY_VERSION=4.2.* SOLR_VERSION=8.0.0 SOLR_CLOUD=false
  - SYMFONY_VERSION=4.2.* SOLR_VERSION=7.7.1 SOLR_CLOUD=true
  - SYMFONY_VERSION=4.2.* SOLR_VERSION=7.7.1 SOLR_CLOUD=false
  - SYMFONY_VERSION=4.2.* SOLR_VERSION=6.6.6 SOLR_CLOUD=false
  - SYMFONY_VERSION=3.3.* SOLR_VERSION=6.6.6 SOLR_CLOUD=false

cache:
  directories:
    - $HOME/.composer/cache
    - solr_downloads

before_install:
  - composer global require "hirak/prestissimo:^0.3"
  - ls solr_downloads/
  - wget -nc --continue -v --tries=3 --directory-prefix=solr_downloads "http://ftp.halifax.rwth-aachen.de/apache/lucene/solr/${SOLR_VERSION}/solr-${SOLR_VERSION}.tgz"
  - tar -xzf solr_downloads/solr-${SOLR_VERSION}.tgz

before_script:
#  - pecl install pecl_http
  - composer require --prefer-source --dev symfony/event-dispatcher:${SYMFONY_VERSION}
  - |
    if [ ${SOLR_CLOUD} == "true" ]; then
       solr-${SOLR_VERSION}/bin/solr start -e cloud -noprompt || travis_terminate 1;
       solr-${SOLR_VERSION}/bin/solr delete -c gettingstarted || travis_terminate 1;
       solr-${SOLR_VERSION}/bin/solr create -c techproducts -s 2 -rf 2 -d solr-${SOLR_VERSION}/server/solr/configsets/sample_techproducts_configs/conf -n sample_techproducts_configs || travis_terminate 1;
       solr-${SOLR_VERSION}/bin/post -c techproducts solr-${SOLR_VERSION}/example/exampledocs/*.xml || travis_terminate 1;
     else
       solr-${SOLR_VERSION}/bin/solr start -e techproducts || travis_terminate 1;
       # make configsets available for techproducts instance for core admin tests
       cp -R solr-${SOLR_VERSION}/server/solr/configsets solr-${SOLR_VERSION}/example/techproducts/solr/ || travis_terminate 1;
    fi

script:
  - |
     if [ ${SOLR_CLOUD} == "true" ]; then
       vendor/bin/phpunit -c phpunit.xml.travis --exclude-group solr_no_cloud -v || travis_terminate 1;
     else
       vendor/bin/phpunit -c phpunit.xml.travis --exclude-group solr_cloud -v || travis_terminate 1;
     fi

after_success:
  - travis_retry php vendor/bin/php-coveralls -v

matrix:
  allow_failures:
      - php: nightly

sudo: false
