site_name: Solarium PHP Solr client library
repo_url: https://github.com/solariumphp/solarium/
theme:
  name: readthedocs
nav:
  - 'Solarium': 'index.md'
  - 'Getting Started': 'getting-started.md'
  - 'Solarium Concepts': 'solarium-concepts.md'
  - 'Client and Adapters': 'client-and-adapters.md'
  - 'Queries':
    - 'queries/select-query/select-query.md'
      - 'queries/select-query/executing-a-select-query.md'
        - 'queries/select-query/building-a-select-query/adding-filterqueries.md'
        - 'queries/select-query/building-a-select-query/building-a-select-query.md'
        - 'queries/select-query/building-a-select-query/components/analytics-component.md'
        - 'queries/select-query/building-a-select-query/components/components.md'
        - 'queries/select-query/building-a-select-query/components/debug-component.md'
        - 'queries/select-query/building-a-select-query/components/dismax-component.md'
        - 'queries/select-query/building-a-select-query/components/distributed-search-component.md'
        - 'queries/select-query/building-a-select-query/components/edismax-component.md'
        - 'queries/select-query/building-a-select-query/components/grouping-component.md'
        - 'queries/select-query/building-a-select-query/components/highlighting-component.md'
        - 'queries/select-query/building-a-select-query/components/morelikethis-component.md'
        - 'queries/select-query/building-a-select-query/components/query-elevation-component.md'
        - 'queries/select-query/building-a-select-query/components/query-rerankquery-component.md'
        - 'queries/select-query/building-a-select-query/components/spellcheck-component.md'
        - 'queries/select-query/building-a-select-query/components/stats-component.md'
        - 'queries/select-query/building-a-select-query/components/termvector-component.md'
        - 'queries/select-query/building-a-select-query/components/facetset-component/facet-field.md'
        - 'queries/select-query/building-a-select-query/components/facetset-component/facet-multiquery.md'
        - 'queries/select-query/building-a-select-query/components/facetset-component/facet-pivot.md'
        - 'queries/select-query/building-a-select-query/components/facetset-component/facet-query.md'
        - 'queries/select-query/building-a-select-query/components/facetset-component/facet-range.md'
        - 'queries/select-query/building-a-select-query/components/facetset-component/facetset-component.md'
      - 'queries/select-query/result-of-a-select-query/result-of-a-select-query.md'
        - 'queries/select-query/result-of-a-select-query/component-results/component-results.md'
        - 'queries/select-query/result-of-a-select-query/component-results/facetset-result.md'
        - 'queries/select-query/result-of-a-select-query/component-results/grouping-result.md'
        - 'queries/select-query/result-of-a-select-query/component-results/highlighting-result.md'
        - 'queries/select-query/result-of-a-select-query/component-results/morelikethis-result.md'
      - 'queries/select-query/re-use-of-queries.md'
    - 'queries/update-query/update-query.md'
      - 'queries/update-query/executing-an-update-query.md'
        - 'queries/update-query/building-an-update-query/add-command.md'
        - 'queries/update-query/building-an-update-query/building-an-update-query.md'
        - 'queries/update-query/building-an-update-query/commit-command.md'
        - 'queries/update-query/building-an-update-query/delete-command.md'
        - 'queries/update-query/building-an-update-query/optimize-command.md'
        - 'queries/update-query/building-an-update-query/rawxml-command.md'
        - 'queries/update-query/building-an-update-query/rollback-command.md'
      - 'queries/update-query/the-result-of-an-update-query.md'
      - 'queries/update-query/best-practices-for-updates.md'
    - 'queries/extract-query.md'
    - 'queries/morelikethis-query.md'
    - 'queries/ping-query.md'
    - 'queries/realtimeget-query.md'
    - 'queries/suggester-query.md'
    - 'queries/terms-query.md'
    - 'Analysis':
      - 'queries/analysis-query/analysis-query.md'
      - 'queries/analysis-query/analysis-document.md'
      - 'queries/analysis-query/analysis-field.md'
    - 'queries/luke-query/luke-query.md'
      - 'queries/luke-query/result-of-a-luke-query/all-fields.md'
      - 'queries/luke-query/result-of-a-luke-query/document.md'
      - 'queries/luke-query/result-of-a-luke-query/field-details.md'
      - 'queries/luke-query/result-of-a-luke-query/index-details.md'
      - 'queries/luke-query/result-of-a-luke-query/info.md'
      - 'queries/luke-query/result-of-a-luke-query/schema.md'
    - 'Managed Resources':
      - 'queries/managedresources-query/managed-resources.md'
      - 'queries/managedresources-query/managed-stopwords.md'
      - 'queries/managedresources-query/managed-synonyms.md'
    - 'queries/server-query/core-admin-query.md'
    - 'Query Helper':
      - 'queries/query-helper/escaping.md'
      - 'queries/query-helper/function-builder.md'
      - 'queries/query-helper/geospatial-support.md'
      - 'queries/query-helper/placeholders.md'
      - 'queries/query-helper/query-helper.md'
  - 'Documents': 'documents.md'
  - 'Customizing': 'customizing-solarium.md'
  - 'Plugins': 'plugins.md'
  - 'Exceptions': 'exceptions.md'
